version: "3"
services:
  django:
    image: szaur/zaur-cloud
    ports:
      - "8000:8000"
      - "80:8000"
    volumes:
      - ./app:/app
      - files:${STORAGE_DIRECTORY}
    env_file: .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: zaur-cloud
    depends_on:
      pgdb:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  test:
    image: szaur/zaur-cloud
    container_name: test
    env_file: .env
    command: >
      /bin/sh -c "python3 manage.py test --no-input"
    volumes:
      - ./app:/app
    depends_on:
      pgdb:
        condition: service_healthy
      redis:
        condition: service_started

  migrate:
    image: szaur/zaur-cloud
    container_name: 'migrate'
    env_file: .env
    command: >
      /bin/sh -c "python3 manage.py makemigrations --force-color --no-input -v 3 && python3 manage.py migrate --force-color -v 3 && python3 manage.py createsuperuser --noinput; exit 0"
    volumes:
      - ./app:/app
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres:13-alpine
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file: .env

volumes:
  pgdbdata: null
  files: null
