# Generated by Django 4.2.7 on 2023-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightresult',
            name='rounds_count',
            field=models.IntegerField(default=1),
        ),
    ]
