# Generated by Django 4.2.4 on 2023-08-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_real_path', models.CharField(max_length=1023)),
                ('path', models.CharField(max_length=1023)),
                ('name', models.CharField(max_length=255)),
                ('is_file', models.BooleanField()),
                ('ext', models.CharField(max_length=31)),
            ],
        ),
    ]
