# Generated by Django 5.0 on 2023-12-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloud', '0005_clipboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clipboard',
        ),
    ]
