# Generated by Django 4.2.4 on 2023-08-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloud', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudobject',
            old_name='_real_path',
            new_name='real_path',
        ),
    ]
