# Generated by Django 4.2.4 on 2023-08-27 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cloud', '0003_rename__real_path_cloudobject_real_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloud.cloudobject')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloud.shared')),
            ],
        ),
    ]
